spring.application.name=backend
# ===============================
# 1. CONEXIÓN A POSTGRESQL (LA MEMORIA)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/taxitel_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# 2. CONFIGURACIÓN DE SPRING DATA JPA (EL TRADUCTOR)
# ===============================
# 'update' le dice a Java que si la tabla no existe, la cree automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Esto te permitirá ver en la consola el código SQL que Java ejecuta por detrás
spring.jpa.show-sql=true